function pug_escape(e){var a=""+e,t=pug_match_html.exec(a);if(!t)return e;var r,c,n,s="";for(r=t.index,c=0;r<a.length;r++){switch(a.charCodeAt(r)){case 34:n="&quot;";break;case 38:n="&amp;";break;case 60:n="&lt;";break;case 62:n="&gt;";break;default:continue}c!==r&&(s+=a.substring(c,r)),c=r+1,s+=n}return c!==r?s+a.substring(c,r):s}
var pug_match_html=/["&<>]/;
function pug_rethrow(n,e,r,t){if(!(n instanceof Error))throw n;if(!("undefined"==typeof window&&e||t))throw n.message+=" on line "+r,n;try{t=t||require("fs").readFileSync(e,"utf8")}catch(e){pug_rethrow(n,null,r)}var i=3,a=t.split("\n"),o=Math.max(r-i,0),h=Math.min(a.length,r+i),i=a.slice(o,h).map(function(n,e){var t=e+o+1;return(t==r?"  > ":"    ")+t+"| "+n}).join("\n");throw n.path=e,n.message=(e||"Pug")+":"+r+"\n"+i+"\n\n"+n.message,n}function renderStockTable(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {;var locals_for_with = (locals || {});(function (Date, products, stock) {;pug_debug_line = 1;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Ctable class=\"table table-responsive-sm table-bordered table-striped table-sm table-light\" id=\"stockTable\"\u003E";
;pug_debug_line = 2;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Cthead\u003E";
;pug_debug_line = 3;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Ctr\u003E";
;pug_debug_line = 4;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Cth\u003E";
;pug_debug_line = 4;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "Name\u003C\u002Fth\u003E";
;pug_debug_line = 5;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Cth\u003E";
;pug_debug_line = 5;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "Type\u003C\u002Fth\u003E";
;pug_debug_line = 6;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Cth\u003E";
;pug_debug_line = 6;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "Brand\u003C\u002Fth\u003E";
;pug_debug_line = 7;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Cth\u003E";
;pug_debug_line = 7;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "Country\u003C\u002Fth\u003E";
;pug_debug_line = 8;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Cth\u003E";
;pug_debug_line = 8;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "Supplier\u003C\u002Fth\u003E";
;pug_debug_line = 9;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Cth\u003E";
;pug_debug_line = 9;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "Size\u003C\u002Fth\u003E";
;pug_debug_line = 10;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Cth\u003E";
;pug_debug_line = 10;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "Quantity\u003C\u002Fth\u003E";
;pug_debug_line = 11;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Cth\u003E";
;pug_debug_line = 11;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "Cost\u003C\u002Fth\u003E";
;pug_debug_line = 12;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Cth\u003E";
;pug_debug_line = 12;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "Place\u003C\u002Fth\u003E";
;pug_debug_line = 13;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Cth\u003E";
;pug_debug_line = 13;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "Date\u003C\u002Fth\u003E\u003C\u002Ftr\u003E\u003C\u002Fthead\u003E";
;pug_debug_line = 14;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Ctbody\u003E";
;pug_debug_line = 15;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
for( let i = 0; i<stock.length;i++){
{
;pug_debug_line = 16;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Ctr\u003E";
;pug_debug_line = 17;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
const idx = products.findIndex(product => product.product_id === stock[i].product_id);
;pug_debug_line = 18;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Ctd\u003E";
;pug_debug_line = 18;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = products[idx].name) ? "" : pug_interp)) + "\u003C\u002Ftd\u003E";
;pug_debug_line = 19;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Ctd\u003E";
;pug_debug_line = 19;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = products[idx].type) ? "" : pug_interp)) + "\u003C\u002Ftd\u003E";
;pug_debug_line = 20;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Ctd\u003E";
;pug_debug_line = 20;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = products[idx].brand) ? "" : pug_interp)) + "\u003C\u002Ftd\u003E";
;pug_debug_line = 21;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Ctd\u003E";
;pug_debug_line = 21;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = products[idx].country) ? "" : pug_interp)) + "\u003C\u002Ftd\u003E";
;pug_debug_line = 22;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Ctd\u003E";
;pug_debug_line = 22;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = stock[i].supplier_name) ? "" : pug_interp)) + "\u003C\u002Ftd\u003E";
;pug_debug_line = 23;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Ctd\u003E";
;pug_debug_line = 23;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = products[idx].size) ? "" : pug_interp)) + "\u003C\u002Ftd\u003E";
;pug_debug_line = 24;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Ctd\u003E";
;pug_debug_line = 24;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = `${stock[i].quantity} ${stock[i].unit}`) ? "" : pug_interp)) + "\u003C\u002Ftd\u003E";
;pug_debug_line = 25;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Ctd\u003E";
;pug_debug_line = 25;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = stock[i].cost) ? "" : pug_interp)) + "\u003C\u002Ftd\u003E";
;pug_debug_line = 26;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Ctd\u003E";
;pug_debug_line = 26;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = stock[i].place) ? "" : pug_interp)) + "\u003C\u002Ftd\u003E";
;pug_debug_line = 27;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
const date = new Date(stock[i].date);
;pug_debug_line = 28;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + "\u003Ctd\u003E";
;pug_debug_line = 28;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = date.toISOString().slice(0,10)) ? "" : pug_interp)) + "\u003C\u002Ftd\u003E\u003C\u002Ftr\u003E";
}
;pug_debug_line = 29;pug_debug_filename = "D:\\Shop-dev\\_views\\_stockTable.pug";
}
pug_html = pug_html + "\u003C\u002Ftbody\u003E\u003C\u002Ftable\u003E";}.call(this,"Date" in locals_for_with?locals_for_with.Date:typeof Date!=="undefined"?Date:undefined,"products" in locals_for_with?locals_for_with.products:typeof products!=="undefined"?products:undefined,"stock" in locals_for_with?locals_for_with.stock:typeof stock!=="undefined"?stock:undefined));} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line);};return pug_html;}